# Generated by Django 5.1 on 2024-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='department',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Department'),
        ),
    ]
