# Generated by Django 5.1 on 2024-09-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='parameter',
            field=models.TextField(blank=True, default='', verbose_name='Parameter'),
        ),
    ]
